# Generated by Django 5.0.6 on 2024-05-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='updated_at',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='created_at',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='contract',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
