# Generated by Django 5.0.6 on 2024-05-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_statuses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractstatus',
            name='description',
        ),
        migrations.AddField(
            model_name='contractstatus',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contractstatus',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
